/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const AchievementCategory = IDL.Variant({
  'certificate' : IDL.Null,
  'researchPaper' : IDL.Null,
  'hackathon' : IDL.Null,
  'project' : IDL.Null,
});
export const AchievementInput = IDL.Record({
  'title' : IDL.Text,
  'certificateImage' : IDL.Opt(ExternalBlob),
  'achievementId' : IDL.Text,
  'studentId' : IDL.Text,
  'date' : Time,
  'studentPrincipal' : IDL.Principal,
  'description' : IDL.Text,
  'links' : IDL.Opt(IDL.Vec(IDL.Text)),
  'category' : AchievementCategory,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VerificationEvent = IDL.Record({
  'status' : VerificationStatus,
  'verifier' : IDL.Principal,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const Achievement = IDL.Record({
  'status' : VerificationStatus,
  'title' : IDL.Text,
  'certificateImage' : IDL.Opt(ExternalBlob),
  'achievementId' : IDL.Text,
  'studentId' : IDL.Text,
  'verificationHistory' : IDL.Vec(VerificationEvent),
  'date' : Time,
  'studentPrincipal' : IDL.Principal,
  'description' : IDL.Text,
  'links' : IDL.Opt(IDL.Vec(IDL.Text)),
  'category' : AchievementCategory,
});
export const Profile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'principal' : IDL.Principal,
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAchievement' : IDL.Func([AchievementInput], [], []),
  'getAchievement' : IDL.Func([IDL.Text], [Achievement], ['query']),
  'getAchievementsByStudentId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'getAchievementsForVerification' : IDL.Func(
      [],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getVerifiedAchievementsByCategory' : IDL.Func(
      [AchievementCategory],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'searchAchievements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'verifyAchievement' : IDL.Func(
      [IDL.Text, VerificationStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const AchievementCategory = IDL.Variant({
    'certificate' : IDL.Null,
    'researchPaper' : IDL.Null,
    'hackathon' : IDL.Null,
    'project' : IDL.Null,
  });
  const AchievementInput = IDL.Record({
    'title' : IDL.Text,
    'certificateImage' : IDL.Opt(ExternalBlob),
    'achievementId' : IDL.Text,
    'studentId' : IDL.Text,
    'date' : Time,
    'studentPrincipal' : IDL.Principal,
    'description' : IDL.Text,
    'links' : IDL.Opt(IDL.Vec(IDL.Text)),
    'category' : AchievementCategory,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VerificationEvent = IDL.Record({
    'status' : VerificationStatus,
    'verifier' : IDL.Principal,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const Achievement = IDL.Record({
    'status' : VerificationStatus,
    'title' : IDL.Text,
    'certificateImage' : IDL.Opt(ExternalBlob),
    'achievementId' : IDL.Text,
    'studentId' : IDL.Text,
    'verificationHistory' : IDL.Vec(VerificationEvent),
    'date' : Time,
    'studentPrincipal' : IDL.Principal,
    'description' : IDL.Text,
    'links' : IDL.Opt(IDL.Vec(IDL.Text)),
    'category' : AchievementCategory,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'principal' : IDL.Principal,
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAchievement' : IDL.Func([AchievementInput], [], []),
    'getAchievement' : IDL.Func([IDL.Text], [Achievement], ['query']),
    'getAchievementsByStudentId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getAchievementsForVerification' : IDL.Func(
        [],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getVerifiedAchievementsByCategory' : IDL.Func(
        [AchievementCategory],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'searchAchievements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'verifyAchievement' : IDL.Func(
        [IDL.Text, VerificationStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };