/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'status' : VerificationStatus,
  'title' : string,
  'certificateImage' : [] | [ExternalBlob],
  'achievementId' : string,
  'studentId' : string,
  'verificationHistory' : Array<VerificationEvent>,
  'date' : Time,
  'studentPrincipal' : Principal,
  'description' : string,
  'links' : [] | [Array<string>],
  'category' : AchievementCategory,
}
export type AchievementCategory = { 'certificate' : null } |
  { 'researchPaper' : null } |
  { 'hackathon' : null } |
  { 'project' : null };
export interface AchievementInput {
  'title' : string,
  'certificateImage' : [] | [ExternalBlob],
  'achievementId' : string,
  'studentId' : string,
  'date' : Time,
  'studentPrincipal' : Principal,
  'description' : string,
  'links' : [] | [Array<string>],
  'category' : AchievementCategory,
}
export type ExternalBlob = Uint8Array;
export interface GeminiChatRequest { 'context' : string, 'message' : string }
export interface GeminiChatResponse { 'answer' : string, 'prompt' : string }
export interface Profile {
  'bio' : [] | [string],
  'principal' : Principal,
  'studentId' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationEvent {
  'status' : VerificationStatus,
  'verifier' : Principal,
  'notes' : [] | [string],
  'timestamp' : Time,
}
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chatWithGemini' : ActorMethod<[GeminiChatRequest], GeminiChatResponse>,
  'createAchievement' : ActorMethod<[AchievementInput], undefined>,
  'getAchievement' : ActorMethod<[string], Achievement>,
  'getAchievementsByStudentId' : ActorMethod<[string], Array<Achievement>>,
  'getAchievementsForVerification' : ActorMethod<[], Array<Achievement>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getVerifiedAchievementsByCategory' : ActorMethod<
    [AchievementCategory],
    Array<Achievement>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchAchievements' : ActorMethod<[string], Array<Achievement>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyAchievement' : ActorMethod<
    [string, VerificationStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];